#spring:
#    thymeleaf:
#        prefix: classpath:/templates/
#        suffix: .html
#        cache: false
#        encoding: utf-8
#        servlet:
#            content-type: text/html
#        check-template-location: true
logging:
  config: classpath:log4j2.yml